

appName: myhelmapp

port: 80

namespace: default

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'Fixed the update issue with helm. This app was deployed with helm!'

image:
  name: devopsjourney1/mywebapp
  tag: latest